DROP PROCEDURE DEPO.EMPLOYEES_ADD;
DROP PROCEDURE DEPO.COMPANIES_ADD;
DROP PROCEDURE DEPO.COMPANIES_GET_ALL;
DROP PROCEDURE DEPO.COMPANIES_GET_BY_ID;
DROP PROCEDURE DEPO.EMPLOYEES_GET_BY_COMPANY;
DROP PROCEDURE DEPO.EMPLOYEES_GET_BY_ID;
DROP PROCEDURE DEPO.COMPANIES_LOAD_FROM_FILE;
DROP PROCEDURE DEPO.EMPLOYEES_LOAD_FROM_FILE;
DROP PROCEDURE DEPO.COMPANIES_LOAD_TO_FILE;
DROP PROCEDURE DEPO.EMPLOYEES_LOAD_TO_FILE;
DROP PROCEDURE DEPO.LOG_ERROR;
DROP PROCEDURE DEPO.GET_TECH_DATA;

DROP TABLE DEPO.EMPLOYEES;
DROP TABLE DEPO.COMPANIES;
DROP TABLE DEPO.ERROR_LOG;
DROP TABLE DEPO.TECH_DATA;
DROP SCHEMA DEPO;